import type { Brand, Category, Product, Model, Vehicle } from './types';

export const mockBrands: Brand[] = [
  {
    id: 'brand-1',
    name: 'MG',
    logo_url: '/placeholder.svg?height=100&width=100',
    country: 'China',
    description: 'Morris Garages - British brand now owned by SAIC',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'brand-2',
    name: 'BYD',
    logo_url: '/placeholder.svg?height=100&width=100',
    country: 'China',
    description: 'Build Your Dreams - Leading EV manufacturer',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'brand-3',
    name: 'Omoda',
    logo_url: '/placeholder.svg?height=100&width=100',
    country: 'China',
    description: "Chery's premium brand",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'brand-4',
    name: 'Geely',
    logo_url: '/placeholder.svg?height=100&width=100',
    country: 'China',
    description: 'Geely Automobile Holdings',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'brand-5',
    name: 'Haval',
    logo_url: '/placeholder.svg?height=100&width=100',
    country: 'China',
    description: 'Great Wall Motors premium SUV brand',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockCategories: Category[] = [
  {
    id: 'cat-1',
    name: 'Engine & Cooling',
    description: 'Engine parts, filters, cooling systems',
    parent_category_id: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-2',
    name: 'Brakes',
    description: 'Brake pads, rotors, brake fluid',
    parent_category_id: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-3',
    name: 'Suspension & Steering',
    description: 'Shocks, springs, tie rods, steering components',
    parent_category_id: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-4',
    name: 'Electrical',
    description: 'Battery, alternator, starter, wiring',
    parent_category_id: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-5',
    name: 'Interior Accessories',
    description: 'Seat covers, floor mats, organizers',
    parent_category_id: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-6',
    name: 'Lighting',
    description: 'Headlights, taillights, LED upgrades',
    parent_category_id: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    sku: 'MG4-OIL-001',
    name: 'Synthetic Engine Oil 5W-30 (5L)',
    category_id: 'cat-1',
    description: 'Premium synthetic oil for MG4',
    price: 45.99,
    stock_quantity: 100,
    specifications: { capacity: '5L', viscosity: '5W-30', type: 'Synthetic' },
    oem_numbers: ['MG4-OIL-001'],
    image_url: '/placeholder.svg?height=300&width=300',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-2',
    sku: 'MG4-BRAKE-001',
    name: 'Front Brake Pads Set',
    category_id: 'cat-2',
    description: 'Ceramic brake pads for smooth braking',
    price: 65.0,
    stock_quantity: 80,
    specifications: { material: 'Ceramic', position: 'Front' },
    oem_numbers: ['MG4-BRAKE-001'],
    image_url: '/placeholder.svg?height=300&width=300',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-3',
    sku: 'MG4-AIR-001',
    name: 'Engine Air Filter',
    category_id: 'cat-1',
    description: 'Original MG4 air filter',
    price: 24.5,
    stock_quantity: 150,
    specifications: { type: 'Air Filter', fitment: 'MG4' },
    oem_numbers: ['MG4-AIR-001', 'A2004700'],
    image_url: '/placeholder.svg?height=300&width=300',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-4',
    sku: 'MG-SEAT-001',
    name: 'Black Leather Seat Covers (Set)',
    category_id: 'cat-5',
    description: 'Premium leather seat covers',
    price: 189.99,
    stock_quantity: 50,
    specifications: { material: 'Leather', color: 'Black', coverage: 'Full Set' },
    oem_numbers: ['MG-SEAT-001'],
    image_url: '/placeholder.svg?height=300&width=300',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-5',
    sku: 'MG-BATTERY-001',
    name: 'Car Battery 60Ah',
    category_id: 'cat-4',
    description: 'Reliable power supply for all MG models',
    price: 145.0,
    stock_quantity: 60,
    specifications: { capacity: '60Ah', voltage: '12V' },
    oem_numbers: ['MG-BATTERY-001'],
    image_url: '/placeholder.svg?height=300&width=300',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'prod-6',
    sku: 'MG4-LED-001',
    name: 'LED Headlight Upgrade Kit',
    category_id: 'cat-6',
    description: 'Modern LED headlights with better visibility',
    price: 299.99,
    stock_quantity: 30,
    specifications: { type: 'LED', brightness: '6000K', fitment: 'MG4' },
    oem_numbers: ['MG4-LED-001'],
    image_url: '/placeholder.svg?height=300&width=300',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

const now = new Date().toISOString();

export const mockModels: Model[] = [
  {
    id: 'model-mg4',
    brand_id: 'brand-1',
    name: 'MG4',
    year_start: 2021,
    year_end: null,
    description: 'Compact EV hatchback',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'model-mg-zs-ev',
    brand_id: 'brand-1',
    name: 'MG ZS EV',
    year_start: 2020,
    year_end: null,
    description: 'Compact electric SUV',
    created_at: now,
    updated_at: now,
  },
];

export const mockVehicles: Vehicle[] = [
  {
    id: 'vehicle-mg4-standard',
    model_id: 'model-mg4',
    variant_name: 'MG4 Standard (44kWh)',
    engine_type: 'Electric',
    transmission: 'Single-speed automatic',
    specifications: {
      displacement: 'EV',
      power_kw: 125,
      battery: '44 kWh',
    },
    created_at: now,
    updated_at: now,
  },
  {
    id: 'vehicle-mg4-long-range',
    model_id: 'model-mg4',
    variant_name: 'MG4 Long Range (61kWh)',
    engine_type: 'Electric',
    transmission: 'Single-speed automatic',
    specifications: {
      displacement: 'EV',
      power_kw: 150,
      battery: '61 kWh',
    },
    created_at: now,
    updated_at: now,
  },
  {
    id: 'vehicle-mgzs-ev-lux',
    model_id: 'model-mg-zs-ev',
    variant_name: 'MG ZS EV Luxury',
    engine_type: 'Electric',
    transmission: 'Single-speed automatic',
    specifications: {
      displacement: 'EV',
      power_kw: 105,
      battery: '51 kWh',
    },
    created_at: now,
    updated_at: now,
  },
];

export const mockVehicleCompatibility: Record<string, string[]> = {
  'vehicle-mg4-standard': ['prod-1', 'prod-2', 'prod-3', 'prod-6'],
  'vehicle-mg4-long-range': ['prod-1', 'prod-3', 'prod-6'],
  'vehicle-mgzs-ev-lux': ['prod-2', 'prod-5'],
};
